
GOOGLE_API_KEY="AIzaSyC7lFa-0ZHvh09Hm4TtYfVc894UQXggLX0"

ZHIPUAI_API_KEY="e40c7971bed9419188881db85f0be9d8.YL9a7Bpt2NpodvMu"
TELEGRAM_BOT_TOKEN="7205320483:AAEE_i7SPprNz7cPGiBPUqmbsOonRP8BkKU"
TELEGRAM_CHAT_ID="7152418567"
TELEGRAM_ENABLED="true"



  